---
# See https://github.com/LizardByte/beautiful-jekyll-next/blob/master/_config.yml for documented options

remote_theme: LizardByte/beautiful-jekyll-next@74d882a18fac005f9735ec7f8a3053d1c3beee3a

title: ReenigneArcher's Blog
author: ReenigneArcher

amazon_products:
  enabled: true
  affiliate_tag: 'lizardbyte-blog-20'

navbar-links:
  About Me: "aboutme"
  Sample Sites:
    - LizardByte: "https://lizardbyte.github.io"
    - Game DB: "https://lizardbyte.github.io/GameDB"
    - Themerr DB: "https://lizardbyte.github.io/ThemerrDB"
    - Corner Brew: "https://tompkinsliving.github.io/corner-brew"
  Tag Index: "tags"
  ‚ù§ Support:
    - GitHub: "https://github.com/sponsors/reenignearcher"
    - PayPal: "https://www.paypal.com/paypalme/ReenigneArcher"

avatar: "/assets/img/my-avatar.png"
round-avatar: true
social-network-links:
  rss: true
  discord: "users/671126231529422877"
  github: reenignearcher
  gitlab: ReenigneArcher
  linkedin: davidlane1987
  patreon: LizardByte
  reddit: reenignearcher
  stackoverflow: "11214013/reenignearcher"
  twitter: ReenigneArcher
rss-description: ReenigneArcher
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  reddit: true
  vk: false
url-pretty: "ReenigneArcher.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: true
keywords: "ReenigneArcher,LizardByte,Sunshine,RetroArcher,blog,programming,open-source"

# Light theme colors
page-col: "#f5f5f5"
text-col: "#212529"
link-col: "#28a9e6"
hover-col: "#1c7fb3"
navbar-col: "#e9ecef"
navbar-text-col: "#212529"
navbar-border-col: "#dee2e6"
footer-col: "#e9ecef"
footer-text-col: "#6c757d"
footer-link-col: "#212529"
footer-hover-col: "#28a9e6"
pygments-theme-light: "pygments-styles/ayu-light"

# Dark theme colors
dark-page-col: "#18191a"
dark-text-col: "#e4e4e4"
dark-link-col: "#28a9e6"
dark-hover-col: "#28a9e6"
dark-navbar-col: "#242526"
dark-navbar-text-col: "#e4e6eb"
dark-navbar-border-col: "#393a3b"
dark-footer-col: "#242526"
dark-footer-text-col: "#a8aaa8"
dark-footer-link-col: "#dfdfdf"
dark-footer-hover-col: "#28a9e6"
pygments-theme-dark: "pygments-styles/ayu-dark"

mobile-theme-col: "#FC7D17"

giscus:
  hostname: giscus.app  # Replace with your giscus instance's hostname if self-hosting
  repository: ReenigneArcher/ReenigneArcher.github.io  # GitHub username/repository eg. "daattali/beautiful-jekyll"
  repository-id: R_kgDOKmEkUQ  # ID of your repository, retrieve this info from https://giscus.app
  category: Blog  # Category name of your GitHub Discussion posts
  category-id: DIC_kwDOKmEkUc4CxMlV  # ID of your category, retrieve this info from https://giscus.app
  mapping: pathname
  strict: 1
  reactions-enabled: 1
  emit-metadata: 0
  input-position: top
  theme: preferred_color_scheme
  lang: en
  lazy-loading: true
date_format: "%B %-d, %Y"

# Advanced settings
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true  # add social media sharing buttons to all blog posts
  -
    scope:
      path: ""  # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from the production site
exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
